/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.programa2.GUI;

/**
 *
 * @author dandi
 */
public class JugarFrame extends javax.swing.JFrame {

      /**
       * Creates new form JugarFrame
       */
      public JugarFrame() {
            initComponents();
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jLabel2 = new javax.swing.JLabel();
            jLabel1 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            NivelTXT = new javax.swing.JLabel();
            jPanel1 = new javax.swing.JPanel();
            Btn03 = new javax.swing.JButton();
            Btn04 = new javax.swing.JButton();
            Btn10 = new javax.swing.JButton();
            Btn11 = new javax.swing.JButton();
            Btn12 = new javax.swing.JButton();
            Btn13 = new javax.swing.JButton();
            Btn14 = new javax.swing.JButton();
            Btn00 = new javax.swing.JButton();
            Btn01 = new javax.swing.JButton();
            Btn02 = new javax.swing.JButton();
            Btn20 = new javax.swing.JButton();
            Btn21 = new javax.swing.JButton();
            Btn22 = new javax.swing.JButton();
            Btn23 = new javax.swing.JButton();
            Btn24 = new javax.swing.JButton();
            Btn44 = new javax.swing.JButton();
            Bt30 = new javax.swing.JButton();
            Btn31 = new javax.swing.JButton();
            Btn32 = new javax.swing.JButton();
            Btn33 = new javax.swing.JButton();
            Btn34 = new javax.swing.JButton();
            Btn40 = new javax.swing.JButton();
            Btn41 = new javax.swing.JButton();
            Btn42 = new javax.swing.JButton();
            Btn43 = new javax.swing.JButton();
            NombreTXT = new javax.swing.JLabel();
            NumbersPanel = new javax.swing.JPanel();
            Btn1 = new javax.swing.JButton();
            Btn2 = new javax.swing.JButton();
            Btn3 = new javax.swing.JButton();
            Btn4 = new javax.swing.JButton();
            Btn5 = new javax.swing.JButton();
            IniciarJuego = new javax.swing.JButton();
            BorrarJugada = new javax.swing.JButton();
            RehacerJugada = new javax.swing.JButton();
            TerminarJuego = new javax.swing.JButton();
            Top11 = new javax.swing.JButton();
            TerminarJuego1 = new javax.swing.JButton();
            GuardarJuego = new javax.swing.JButton();
            CargarJuego = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setBackground(new java.awt.Color(255, 255, 255));

            jLabel2.setBackground(new java.awt.Color(255, 0, 0));
            jLabel2.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
            jLabel2.setText("Futoshiki");

            jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            jLabel1.setText("NIVEL");

            jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            jLabel3.setText("Nombre del jugador");

            NivelTXT.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

            Btn03.setBackground(new java.awt.Color(255, 255, 255));

            Btn04.setBackground(new java.awt.Color(255, 255, 255));

            Btn10.setBackground(new java.awt.Color(255, 255, 255));

            Btn11.setBackground(new java.awt.Color(255, 255, 255));

            Btn12.setBackground(new java.awt.Color(255, 255, 255));

            Btn13.setBackground(new java.awt.Color(255, 255, 255));

            Btn14.setBackground(new java.awt.Color(255, 255, 255));

            Btn00.setBackground(new java.awt.Color(255, 255, 255));

            Btn01.setBackground(new java.awt.Color(255, 255, 255));
            Btn01.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Btn01ActionPerformed(evt);
                  }
            });

            Btn02.setBackground(new java.awt.Color(255, 255, 255));

            Btn20.setBackground(new java.awt.Color(255, 255, 255));

            Btn21.setBackground(new java.awt.Color(255, 255, 255));

            Btn22.setBackground(new java.awt.Color(255, 255, 255));

            Btn23.setBackground(new java.awt.Color(255, 255, 255));

            Btn24.setBackground(new java.awt.Color(255, 255, 255));

            Btn44.setBackground(new java.awt.Color(255, 255, 255));

            Bt30.setBackground(new java.awt.Color(255, 255, 255));

            Btn31.setBackground(new java.awt.Color(255, 255, 255));

            Btn32.setBackground(new java.awt.Color(255, 255, 255));

            Btn33.setBackground(new java.awt.Color(255, 255, 255));

            Btn34.setBackground(new java.awt.Color(255, 255, 255));

            Btn40.setBackground(new java.awt.Color(255, 255, 255));

            Btn41.setBackground(new java.awt.Color(255, 255, 255));

            Btn42.setBackground(new java.awt.Color(255, 255, 255));

            Btn43.setBackground(new java.awt.Color(255, 255, 255));

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(Bt30, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(Btn40, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(Btn42, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(44, 44, 44)
                                                .addComponent(Btn43, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(47, 47, 47)
                                                .addComponent(Btn44, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Btn32, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(44, 44, 44)
                                                .addComponent(Btn33, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(47, 47, 47)
                                                .addComponent(Btn34, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                          .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(Btn00, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addComponent(Btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, 0))
                                          .addComponent(Btn20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                  .addComponent(Btn01, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                  .addGap(45, 45, 45)
                                                                  .addComponent(Btn02, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                  .addComponent(Btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                  .addComponent(Btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                      .addGap(44, 44, 44)
                                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(Btn03, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(Btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                      .addGap(47, 47, 47)
                                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(Btn04, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(Btn14, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(Btn31, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Btn41, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(160, 160, 160)
                                                .addComponent(Btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(44, 44, 44)
                                                .addComponent(Btn23, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(47, 47, 47)
                                                .addComponent(Btn24, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(408, 408, 408))
            );
            jPanel1Layout.setVerticalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(Btn02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(Btn03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(Btn04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(Btn00, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(45, 45, 45))
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Btn01, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                          .addComponent(Btn12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(Btn11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(Btn10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addComponent(Btn14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(Btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(Btn21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(Btn22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(Btn23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(Btn24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                              .addComponent(Btn31, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(Bt30, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(Btn32, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(Btn33, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(Btn34, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Btn40, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn41, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn42, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn43, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addComponent(Btn44, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            NombreTXT.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            NombreTXT.setText("hola");

            Btn1.setBackground(new java.awt.Color(255, 255, 255));
            Btn1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Btn1.setForeground(new java.awt.Color(0, 0, 0));
            Btn1.setText("1");
            Btn1.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Btn1ActionPerformed(evt);
                  }
            });

            Btn2.setBackground(new java.awt.Color(255, 255, 255));
            Btn2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Btn2.setForeground(new java.awt.Color(0, 0, 0));
            Btn2.setText("2");
            Btn2.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Btn2ActionPerformed(evt);
                  }
            });

            Btn3.setBackground(new java.awt.Color(255, 255, 255));
            Btn3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Btn3.setForeground(new java.awt.Color(0, 0, 0));
            Btn3.setText("3");
            Btn3.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Btn3ActionPerformed(evt);
                  }
            });

            Btn4.setBackground(new java.awt.Color(255, 255, 255));
            Btn4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Btn4.setForeground(new java.awt.Color(0, 0, 0));
            Btn4.setText("4");
            Btn4.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Btn4ActionPerformed(evt);
                  }
            });

            Btn5.setBackground(new java.awt.Color(255, 255, 255));
            Btn5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Btn5.setForeground(new java.awt.Color(0, 0, 0));
            Btn5.setText("5");
            Btn5.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Btn5ActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout NumbersPanelLayout = new javax.swing.GroupLayout(NumbersPanel);
            NumbersPanel.setLayout(NumbersPanelLayout);
            NumbersPanelLayout.setHorizontalGroup(
                  NumbersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NumbersPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(NumbersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                              .addComponent(Btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(Btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(Btn3, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                              .addComponent(Btn4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                              .addComponent(Btn5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                        .addGap(24, 24, 24))
            );
            NumbersPanelLayout.setVerticalGroup(
                  NumbersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(NumbersPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(Btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
            );

            IniciarJuego.setBackground(new java.awt.Color(204, 0, 0));
            IniciarJuego.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            IniciarJuego.setForeground(new java.awt.Color(0, 0, 0));
            IniciarJuego.setText("Iniciar Juego");

            BorrarJugada.setBackground(new java.awt.Color(0, 204, 255));
            BorrarJugada.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            BorrarJugada.setForeground(new java.awt.Color(0, 0, 0));
            BorrarJugada.setText("Borrar Jugada");

            RehacerJugada.setBackground(new java.awt.Color(255, 153, 0));
            RehacerJugada.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            RehacerJugada.setForeground(new java.awt.Color(0, 0, 0));
            RehacerJugada.setText("Rehacer Jugada");

            TerminarJuego.setBackground(new java.awt.Color(0, 153, 0));
            TerminarJuego.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            TerminarJuego.setForeground(new java.awt.Color(0, 0, 0));
            TerminarJuego.setText("Terminar Juego");

            Top11.setBackground(new java.awt.Color(255, 255, 0));
            Top11.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Top11.setForeground(new java.awt.Color(0, 0, 0));
            Top11.setText("Top 10");

            TerminarJuego1.setBackground(new java.awt.Color(153, 204, 255));
            TerminarJuego1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            TerminarJuego1.setForeground(new java.awt.Color(0, 0, 0));
            TerminarJuego1.setText("Borrar Juego");

            GuardarJuego.setBackground(new java.awt.Color(255, 255, 255));
            GuardarJuego.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            GuardarJuego.setForeground(new java.awt.Color(0, 0, 0));
            GuardarJuego.setText("Guardar Juego");

            CargarJuego.setBackground(new java.awt.Color(255, 255, 255));
            CargarJuego.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            CargarJuego.setForeground(new java.awt.Color(0, 0, 0));
            CargarJuego.setText("Cargar Juego");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(NivelTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addComponent(NombreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(Top11)
                                                      .addComponent(NumbersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(354, 354, 354)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(166, 166, 166)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                          .addGroup(layout.createSequentialGroup()
                                                .addComponent(IniciarJuego)
                                                .addGap(27, 27, 27)
                                                .addComponent(BorrarJugada))
                                          .addComponent(TerminarJuego))
                                    .addGap(40, 40, 40)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(RehacerJugada)
                                          .addGroup(layout.createSequentialGroup()
                                                .addComponent(TerminarJuego1)
                                                .addGap(57, 57, 57)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(CargarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addComponent(GuardarJuego))))))
                        .addGap(0, 59, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(NivelTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(25, 25, 25)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                          .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(NombreTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NumbersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(IniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(BorrarJugada, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(RehacerJugada, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(Top11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                          .addComponent(TerminarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(TerminarJuego1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(GuardarJuego)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CargarJuego)))
                        .addContainerGap())
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

      private void Btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn01ActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_Btn01ActionPerformed

      private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_Btn1ActionPerformed

      private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_Btn2ActionPerformed

      private void Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn3ActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_Btn3ActionPerformed

      private void Btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn4ActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_Btn4ActionPerformed

      private void Btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn5ActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_Btn5ActionPerformed

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(JugarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(JugarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(JugarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(JugarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new JugarFrame().setVisible(true);
                  }
            });
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton BorrarJugada;
      private javax.swing.JButton Bt30;
      private javax.swing.JButton Btn00;
      private javax.swing.JButton Btn01;
      private javax.swing.JButton Btn02;
      private javax.swing.JButton Btn03;
      private javax.swing.JButton Btn04;
      private javax.swing.JButton Btn1;
      private javax.swing.JButton Btn10;
      private javax.swing.JButton Btn11;
      private javax.swing.JButton Btn12;
      private javax.swing.JButton Btn13;
      private javax.swing.JButton Btn14;
      private javax.swing.JButton Btn2;
      private javax.swing.JButton Btn20;
      private javax.swing.JButton Btn21;
      private javax.swing.JButton Btn22;
      private javax.swing.JButton Btn23;
      private javax.swing.JButton Btn24;
      private javax.swing.JButton Btn3;
      private javax.swing.JButton Btn31;
      private javax.swing.JButton Btn32;
      private javax.swing.JButton Btn33;
      private javax.swing.JButton Btn34;
      private javax.swing.JButton Btn4;
      private javax.swing.JButton Btn40;
      private javax.swing.JButton Btn41;
      private javax.swing.JButton Btn42;
      private javax.swing.JButton Btn43;
      private javax.swing.JButton Btn44;
      private javax.swing.JButton Btn5;
      private javax.swing.JButton CargarJuego;
      private javax.swing.JButton GuardarJuego;
      private javax.swing.JButton IniciarJuego;
      private javax.swing.JLabel NivelTXT;
      private javax.swing.JLabel NombreTXT;
      private javax.swing.JPanel NumbersPanel;
      private javax.swing.JButton RehacerJugada;
      private javax.swing.JButton TerminarJuego;
      private javax.swing.JButton TerminarJuego1;
      private javax.swing.JButton Top11;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JPanel jPanel1;
      // End of variables declaration//GEN-END:variables
}
