/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.programa2.GUI;

/**
 *
 * @author dandi
 */
public class JugarFrame extends javax.swing.JFrame {
      private final char and = '∧';
      private final char or = '∨';
      /**
       * Creates new form JugarFrame
       */
      public JugarFrame() {
            initComponents();
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jLabel2 = new javax.swing.JLabel();
            jLabel1 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            NivelTXT = new javax.swing.JLabel();
            jPanel1 = new javax.swing.JPanel();
            Btn03 = new javax.swing.JButton();
            Btn04 = new javax.swing.JButton();
            Btn10 = new javax.swing.JButton();
            Btn11 = new javax.swing.JButton();
            Btn12 = new javax.swing.JButton();
            Btn13 = new javax.swing.JButton();
            Btn14 = new javax.swing.JButton();
            Btn00 = new javax.swing.JButton();
            Btn01 = new javax.swing.JButton();
            Btn02 = new javax.swing.JButton();
            Btn20 = new javax.swing.JButton();
            Btn21 = new javax.swing.JButton();
            Btn22 = new javax.swing.JButton();
            Btn23 = new javax.swing.JButton();
            Btn24 = new javax.swing.JButton();
            Btn44 = new javax.swing.JButton();
            Bt30 = new javax.swing.JButton();
            Btn31 = new javax.swing.JButton();
            Btn32 = new javax.swing.JButton();
            Btn33 = new javax.swing.JButton();
            Btn34 = new javax.swing.JButton();
            Btn40 = new javax.swing.JButton();
            Btn41 = new javax.swing.JButton();
            Btn42 = new javax.swing.JButton();
            Btn43 = new javax.swing.JButton();
            panelgrid = new javax.swing.JPanel();
            Op001 = new javax.swing.JLabel();
            Op101 = new javax.swing.JLabel();
            Op201 = new javax.swing.JLabel();
            Op301 = new javax.swing.JLabel();
            Op501 = new javax.swing.JLabel();
            jPanel3 = new javax.swing.JPanel();
            Op012 = new javax.swing.JLabel();
            Op112 = new javax.swing.JLabel();
            Op212 = new javax.swing.JLabel();
            Op312 = new javax.swing.JLabel();
            Op412 = new javax.swing.JLabel();
            jPanel4 = new javax.swing.JPanel();
            Op023 = new javax.swing.JLabel();
            Op123 = new javax.swing.JLabel();
            Op223 = new javax.swing.JLabel();
            Op323 = new javax.swing.JLabel();
            Op423 = new javax.swing.JLabel();
            jPanel5 = new javax.swing.JPanel();
            jPanel6 = new javax.swing.JPanel();
            Op034 = new javax.swing.JLabel();
            Op134 = new javax.swing.JLabel();
            Op234 = new javax.swing.JLabel();
            Op334 = new javax.swing.JLabel();
            Op434 = new javax.swing.JLabel();
            NombreTXT = new javax.swing.JLabel();
            NumbersPanel = new javax.swing.JPanel();
            Btn1 = new javax.swing.JButton();
            Btn2 = new javax.swing.JButton();
            Btn3 = new javax.swing.JButton();
            Btn4 = new javax.swing.JButton();
            Btn5 = new javax.swing.JButton();
            IniciarJuego = new javax.swing.JButton();
            BorrarJugada = new javax.swing.JButton();
            RehacerJugada = new javax.swing.JButton();
            TerminarJuego = new javax.swing.JButton();
            Top11 = new javax.swing.JButton();
            TerminarJuego1 = new javax.swing.JButton();
            GuardarJuego = new javax.swing.JButton();
            CargarJuego = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setBackground(new java.awt.Color(255, 255, 255));
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel2.setBackground(new java.awt.Color(153, 0, 0));
            jLabel2.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
            jLabel2.setText("Futoshiki");
            jLabel2.setOpaque(true);
            getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 0, 110, -1));

            jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            jLabel1.setText("NIVEL");
            getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 51, -1, -1));

            jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            jLabel3.setText("Nombre del jugador");
            getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 101, -1, -1));

            NivelTXT.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            getContentPane().add(NivelTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 51, 380, 25));

            jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            Btn03.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Btn03, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 27, 55, 47));

            Btn04.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Btn04, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 27, 55, 47));

            Btn10.setBackground(new java.awt.Color(255, 255, 255));
            Btn10.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Btn10ActionPerformed(evt);
                  }
            });
            jPanel1.add(Btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 119, 50, 47));

            Btn11.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 119, 55, 47));

            Btn12.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 55, 47));

            Btn13.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Btn13, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 119, 55, 47));

            Btn14.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Btn14, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 119, 55, 47));

            Btn00.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Btn00, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 27, 55, 47));

            Btn01.setBackground(new java.awt.Color(255, 255, 255));
            Btn01.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Btn01ActionPerformed(evt);
                  }
            });
            jPanel1.add(Btn01, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 27, 55, 47));

            Btn02.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Btn02, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 27, 55, 47));

            Btn20.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Btn20, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 193, 55, 47));

            Btn21.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Btn21, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 193, 55, 47));

            Btn22.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Btn22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 55, 47));

            Btn23.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Btn23, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 190, 50, 47));

            Btn24.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Btn24, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 55, 47));

            Btn44.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Btn44, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 355, 55, 47));

            Bt30.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Bt30, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 276, 55, 47));

            Btn31.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Btn31, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 276, 55, 47));

            Btn32.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Btn32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 277, 55, 50));

            Btn33.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Btn33, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 276, 50, 50));

            Btn34.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Btn34, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 276, 55, 47));

            Btn40.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Btn40, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 355, 55, 47));

            Btn41.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Btn41, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 50, 50));

            Btn42.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Btn42, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 55, 50));

            Btn43.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.add(Btn43, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 55, 47));

            panelgrid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            Op001.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Op001.setText("hhhhhh");
            panelgrid.add(Op001, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 41, -1, -1));

            Op101.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
            Op101.setText(">");
            panelgrid.add(Op101, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 20, -1));

            Op201.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Op201.setText("∧");
            panelgrid.add(Op201, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 206, -1, -1));

            Op301.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Op301.setText("∨");
            panelgrid.add(Op301, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 293, -1, -1));

            Op501.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Op501.setText("jLabel4");
            panelgrid.add(Op501, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 366, -1, -1));

            jPanel1.add(panelgrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 0, -1, 402));

            jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            Op012.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Op012.setText("jLabel4");
            jPanel3.add(Op012, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 30, -1, -1));

            Op112.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Op112.setText("jLabel4");
            jPanel3.add(Op112, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 126, -1, -1));

            Op212.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Op212.setText("jLabel4");
            jPanel3.add(Op212, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 194, -1, -1));

            Op312.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Op312.setText("jLabel4");
            jPanel3.add(Op312, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 281, -1, -1));

            Op412.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Op412.setText("jLabel4");
            jPanel3.add(Op412, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 357, -1, -1));

            jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 50, 400));

            jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            Op023.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Op023.setText("jLabel4");
            jPanel4.add(Op023, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 46, -1));

            Op123.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Op123.setText("jLabel4");
            jPanel4.add(Op123, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 113, -1, -1));

            Op223.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Op223.setText("jLabel4");
            jPanel4.add(Op223, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 183, -1, -1));

            Op323.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Op323.setText("jLabel4");
            jPanel4.add(Op323, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 273, -1, -1));

            Op423.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Op423.setText("jLabel4");
            jPanel4.add(Op423, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 346, -1, -1));

            jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 40, 400));

            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                  jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 40, Short.MAX_VALUE)
            );
            jPanel5Layout.setVerticalGroup(
                  jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 100, Short.MAX_VALUE)
            );

            jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 40, -1));

            jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            Op034.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Op034.setText("jLabel4");
            jPanel6.add(Op034, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 20, -1, -1));

            Op134.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Op134.setText("jLabel4");
            jPanel6.add(Op134, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 112, -1, -1));

            Op234.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Op234.setText("jLabel4");
            jPanel6.add(Op234, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 182, -1, -1));

            Op334.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Op334.setText("jLabel4");
            jPanel6.add(Op334, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 271, -1, -1));

            Op434.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Op434.setText("jLabel4");
            jPanel6.add(Op434, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 348, -1, -1));

            jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 50, 390));

            getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 144, 486, 415));

            NombreTXT.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            NombreTXT.setText("hola");
            getContentPane().add(NombreTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 101, 299, -1));

            NumbersPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            Btn1.setBackground(new java.awt.Color(255, 255, 255));
            Btn1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Btn1.setForeground(new java.awt.Color(0, 0, 0));
            Btn1.setText("1");
            Btn1.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Btn1ActionPerformed(evt);
                  }
            });
            NumbersPanel.add(Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 11, 51, 48));

            Btn2.setBackground(new java.awt.Color(255, 255, 255));
            Btn2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Btn2.setForeground(new java.awt.Color(0, 0, 0));
            Btn2.setText("2");
            Btn2.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Btn2ActionPerformed(evt);
                  }
            });
            NumbersPanel.add(Btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 98, 51, 48));

            Btn3.setBackground(new java.awt.Color(255, 255, 255));
            Btn3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Btn3.setForeground(new java.awt.Color(0, 0, 0));
            Btn3.setText("3");
            Btn3.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Btn3ActionPerformed(evt);
                  }
            });
            NumbersPanel.add(Btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 175, 51, 48));

            Btn4.setBackground(new java.awt.Color(255, 255, 255));
            Btn4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Btn4.setForeground(new java.awt.Color(0, 0, 0));
            Btn4.setText("4");
            Btn4.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Btn4ActionPerformed(evt);
                  }
            });
            NumbersPanel.add(Btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 260, 51, 48));

            Btn5.setBackground(new java.awt.Color(255, 255, 255));
            Btn5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Btn5.setForeground(new java.awt.Color(0, 0, 0));
            Btn5.setText("5");
            Btn5.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Btn5ActionPerformed(evt);
                  }
            });
            NumbersPanel.add(Btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 335, 51, 48));

            getContentPane().add(NumbersPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 151, -1, -1));

            IniciarJuego.setBackground(new java.awt.Color(204, 0, 0));
            IniciarJuego.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            IniciarJuego.setForeground(new java.awt.Color(0, 0, 0));
            IniciarJuego.setText("Iniciar Juego");
            getContentPane().add(IniciarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 577, -1, 52));

            BorrarJugada.setBackground(new java.awt.Color(0, 204, 255));
            BorrarJugada.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            BorrarJugada.setForeground(new java.awt.Color(0, 0, 0));
            BorrarJugada.setText("Borrar Jugada");
            getContentPane().add(BorrarJugada, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 577, -1, 52));

            RehacerJugada.setBackground(new java.awt.Color(255, 153, 0));
            RehacerJugada.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            RehacerJugada.setForeground(new java.awt.Color(0, 0, 0));
            RehacerJugada.setText("Rehacer Jugada");
            getContentPane().add(RehacerJugada, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 577, -1, 52));

            TerminarJuego.setBackground(new java.awt.Color(0, 153, 0));
            TerminarJuego.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            TerminarJuego.setForeground(new java.awt.Color(0, 0, 0));
            TerminarJuego.setText("Terminar Juego");
            getContentPane().add(TerminarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 640, -1, 52));

            Top11.setBackground(new java.awt.Color(255, 255, 0));
            Top11.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            Top11.setForeground(new java.awt.Color(0, 0, 0));
            Top11.setText("Top 10");
            getContentPane().add(Top11, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 577, -1, 52));

            TerminarJuego1.setBackground(new java.awt.Color(153, 204, 255));
            TerminarJuego1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            TerminarJuego1.setForeground(new java.awt.Color(0, 0, 0));
            TerminarJuego1.setText("Borrar Juego");
            getContentPane().add(TerminarJuego1, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 640, -1, 52));

            GuardarJuego.setBackground(new java.awt.Color(255, 255, 255));
            GuardarJuego.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            GuardarJuego.setForeground(new java.awt.Color(0, 0, 0));
            GuardarJuego.setText("Guardar Juego");
            getContentPane().add(GuardarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 635, -1, -1));

            CargarJuego.setBackground(new java.awt.Color(255, 255, 255));
            CargarJuego.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            CargarJuego.setForeground(new java.awt.Color(0, 0, 0));
            CargarJuego.setText("Cargar Juego");
            getContentPane().add(CargarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 675, 150, -1));

            pack();
      }// </editor-fold>//GEN-END:initComponents

      private void Btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn01ActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_Btn01ActionPerformed

      private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_Btn1ActionPerformed

      private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_Btn2ActionPerformed

      private void Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn3ActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_Btn3ActionPerformed

      private void Btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn4ActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_Btn4ActionPerformed

      private void Btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn5ActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_Btn5ActionPerformed

      private void Btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn10ActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_Btn10ActionPerformed

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(JugarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(JugarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(JugarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(JugarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new JugarFrame().setVisible(true);
                  }
            });
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton BorrarJugada;
      private javax.swing.JButton Bt30;
      private javax.swing.JButton Btn00;
      private javax.swing.JButton Btn01;
      private javax.swing.JButton Btn02;
      private javax.swing.JButton Btn03;
      private javax.swing.JButton Btn04;
      private javax.swing.JButton Btn1;
      private javax.swing.JButton Btn10;
      private javax.swing.JButton Btn11;
      private javax.swing.JButton Btn12;
      private javax.swing.JButton Btn13;
      private javax.swing.JButton Btn14;
      private javax.swing.JButton Btn2;
      private javax.swing.JButton Btn20;
      private javax.swing.JButton Btn21;
      private javax.swing.JButton Btn22;
      private javax.swing.JButton Btn23;
      private javax.swing.JButton Btn24;
      private javax.swing.JButton Btn3;
      private javax.swing.JButton Btn31;
      private javax.swing.JButton Btn32;
      private javax.swing.JButton Btn33;
      private javax.swing.JButton Btn34;
      private javax.swing.JButton Btn4;
      private javax.swing.JButton Btn40;
      private javax.swing.JButton Btn41;
      private javax.swing.JButton Btn42;
      private javax.swing.JButton Btn43;
      private javax.swing.JButton Btn44;
      private javax.swing.JButton Btn5;
      private javax.swing.JButton CargarJuego;
      private javax.swing.JButton GuardarJuego;
      private javax.swing.JButton IniciarJuego;
      private javax.swing.JLabel NivelTXT;
      private javax.swing.JLabel NombreTXT;
      private javax.swing.JPanel NumbersPanel;
      private javax.swing.JLabel Op001;
      private javax.swing.JLabel Op012;
      private javax.swing.JLabel Op023;
      private javax.swing.JLabel Op034;
      private javax.swing.JLabel Op101;
      private javax.swing.JLabel Op112;
      private javax.swing.JLabel Op123;
      private javax.swing.JLabel Op134;
      private javax.swing.JLabel Op201;
      private javax.swing.JLabel Op212;
      private javax.swing.JLabel Op223;
      private javax.swing.JLabel Op234;
      private javax.swing.JLabel Op301;
      private javax.swing.JLabel Op312;
      private javax.swing.JLabel Op323;
      private javax.swing.JLabel Op334;
      private javax.swing.JLabel Op412;
      private javax.swing.JLabel Op423;
      private javax.swing.JLabel Op434;
      private javax.swing.JLabel Op501;
      private javax.swing.JButton RehacerJugada;
      private javax.swing.JButton TerminarJuego;
      private javax.swing.JButton TerminarJuego1;
      private javax.swing.JButton Top11;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JPanel jPanel1;
      private javax.swing.JPanel jPanel3;
      private javax.swing.JPanel jPanel4;
      private javax.swing.JPanel jPanel5;
      private javax.swing.JPanel jPanel6;
      private javax.swing.JPanel panelgrid;
      // End of variables declaration//GEN-END:variables
}
