/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.programa2.GUI;

/**
 *
 * @author dandi
 */
public class Top10Frame extends javax.swing.JFrame {

      /**
       * Creates new form Top10Frame
       */
      public Top10Frame() {
            initComponents();
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jScrollPane1 = new javax.swing.JScrollPane();
            FacilList = new javax.swing.JList<>();
            jScrollPane2 = new javax.swing.JScrollPane();
            IntermedioList = new javax.swing.JList<>();
            jScrollPane3 = new javax.swing.JScrollPane();
            DificilList = new javax.swing.JList<>();
            CerrarButton = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel1.setBackground(new java.awt.Color(255, 255, 0));
            jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(0, 0, 0));
            jLabel1.setText("Top 10");
            jLabel1.setOpaque(true);
            getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

            jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
            jLabel2.setText("NIVEL FÁCIL:");
            getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

            jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
            jLabel3.setText("NIVEL INTERMEDIO:");
            getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

            jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
            jLabel4.setText("NIVEL DIFÍCIL:");
            getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

            FacilList.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
            jScrollPane1.setViewportView(FacilList);

            getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 290, 170));

            IntermedioList.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
            jScrollPane2.setViewportView(IntermedioList);

            getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 290, 150));

            DificilList.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
            jScrollPane3.setViewportView(DificilList);

            getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 290, 160));

            CerrarButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
            CerrarButton.setText("Cerrar");
            getContentPane().add(CerrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 100, 50));

            pack();
      }// </editor-fold>//GEN-END:initComponents

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(Top10Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(Top10Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(Top10Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(Top10Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new Top10Frame().setVisible(true);
                  }
            });
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton CerrarButton;
      private javax.swing.JList<String> DificilList;
      private javax.swing.JList<String> FacilList;
      private javax.swing.JList<String> IntermedioList;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JLabel jLabel4;
      private javax.swing.JScrollPane jScrollPane1;
      private javax.swing.JScrollPane jScrollPane2;
      private javax.swing.JScrollPane jScrollPane3;
      // End of variables declaration//GEN-END:variables
}
